### DISCUSSION TITLE
Voltage control

### DISCUSSION THREAD

**Discussion by tomkolp** [odya/esphome-powmr-hybrid-inverter#15] [Q&A]
I have POW-HVM1.5H-12V, will it be possible to control the voltages?

In the smartess application, it is not possible to control the voltages for 12v.  There is only a choice of 24v or 48v.  

Has anyone tested this integration with a 12v inverter?

**Comment by odya** [comment]
Sorry, I have only 24v model. What voltages are you talking about?

**Comment by odya** [comment]
For now it were tested only on 2.4kW/24v model. I added a manuals section because during my research, I accumulated various manuals. I assumed that the 1.5, 2.0, 2.4, and 3.2 models are similar because they have mostly similar manuals. I apologize for any confusion.

**Comment by Paxy** [comment]
Have you tried to make a switch instead of the sensor for writing Modbus value instead of just reading it? This could be useful for remote voltage control, power source selection, ...
Do you have yaml sample with switches that works?

**Comment by odya** [comment]
There are separate registers for reading and writing. I am using the [modbus_select](https://esphome.io/components/select/modbus_controller) component for changing write registers. For binary values, you can use the Modbus Switch component instead.

So, in principle, you can use [modbus_switch](https://esphome.io/components/switch/modbus_controller) to change the values of write registers from the [list](https://esphome.io/components/switch/modbus_controller).

**Comment by mehrdadbtit** [comment]
Hi, I have a 10.2kw unit and am trying to change the threshold voltage for back to utility and back to battery (registers 5025 and 5026) but can't figure out the mapping (if any) of the voltages and value to pass on to the register. any idea/suggestion of things to try?

Thanks

**Reply by aver-ua** [reply]
try this

```yaml
number:
  - platform: modbus_controller
    name: "Back To Utility Source Voltage"
    skip_updates: ${select_skip_updates}
    entity_category: config
    address: 5025
    value_type: U_WORD
    force_new_range: true
    min_value: 42
    max_value: 51
    step: 1
    multiply: 10
  - platform: modbus_controller
    name: "Back To Battery Source Voltage"
    skip_updates: ${select_skip_updates}
    entity_category: config
    address: 5026
    value_type: U_WORD
    min_value: 48
    max_value: 54
    step: 1
    multiply: 10

```
