### DISCUSSION TITLE
SunSynk Power Flow Card - PowMr Support

### DISCUSSION THREAD

**Discussion by Roving-Ronin** [odya/esphome-powmr-hybrid-inverter#35] [Show and tell]
Hi,

FYI PowMr is now available as an option from the choice of inverters, in the SunSynk Power Flow Card.

https://github.com/slipx06/sunsynk-power-flow-card/issues/352#issuecomment-2035024166

To use:

```
inverter:
  modern: false
  colour: grey
  autarky: power
  auto_scale: true
  model: powmr
  three_phase: false
```
