### DISCUSSION TITLE
Inverter_Example Yaml Error - Includes references ESPHome /includes directory for common sensors

### DISCUSSION THREAD

**Discussion by Roving-Ronin** [odya/esphome-powmr-hybrid-inverter#38] [General]
@odya,

Just looking and noticed that your inverter-example.yaml (at https://github.com/odya/esphome-powmr-hybrid-inverter/blob/main/examples/powmr-inverter.yaml ) contains the following:

```
packages:
  main: !include powmr-inverter/main.yaml
  # You can replace next 2 lines with your common configs for all devices
  common_system: !include includes/common_system.yaml
  common_sensors: !include includes/common_sensors.yaml
```

This is actually referencing /esphome/includes directory, which I note you don't have an 'includes' directory on this repository, to share these files.
