### ISSUE TITLE
POW-HVM4.2M-24V some issues

### ISSUE THREAD

**Issue by aver-ua** [odya/esphome-powmr-hybrid-inverter#26]
hi. thanks a lot for your work.
i have POW-HVM4.2M-24V inverter. 
there are some issues that i found.
1. sensor "Charger Status" displays "0d00". what does it mean?
2. sensor "Controller Temperature" dispalys "70,6 °C". it's some kind of mistake. it can't be that high..
3. this invertor model has "Max Total Charging Current" = 140A (max) and "Max Utility Charging Current" = 100A (max). so the corresponding selects "Max Total Charge Current" and "Utility Charge Current" are not displayed normally and have an unknown value. how can i fix this?

**Comment by Andreychik32** [comment]
@aver-ua, to fix `Charger Status`, you can use this config I made:
```yaml
  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "Charger Status"
    address: 4555
    register_type: holding
    response_size: 2
    raw_encode: HEXBYTES
    lambda: |-
      uint16_t sensorIndex = swapBytes(modbus_controller::word_from_hex_str(x, 0));
      uint8_t byte = sensorIndex & 0x7;
      switch (byte) {
        case 2: return std::string("Off");
        case 5: return std::string("Idle");
        case 4: return std::string("Charging");
        default: return std::string(x);
      }
```

And thanks for your fix to `Grid Active` and `On Battery` sensors!
