### ISSUE TITLE
Compiling for esp32c3 

### ISSUE THREAD

**Issue by bronzeblood** [odya/esphome-powmr-hybrid-inverter#27]
What parameters need to be changed to use it with the advanced pcb that @davidebeatrici designed. I can get it to compile but the esp just boot loops.

**Comment by bronzeblood** [comment]
ok i got it to compile by replacing this..

```
esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
```
Seems like my boot loop was caused by low voltage from the usb uart i was using, when powered from the inverter its starting fine. 

However i'm not getting any communication, can someone clarify the gpio pins used for tx/rx on the advanced design.
