### ISSUE TITLE
PV Power from POW-HVM10.2M seems to only show one of the two PV string

### ISSUE THREAD

**Issue by pkirk** [odya/esphome-powmr-hybrid-inverter#31]
Gentleman,
I have two PV strings to my inverter(4 + 4kW) , but the register 4505 seems to show only one. The same thing is on the physical display of the Inverter, where only one string at a time is showed, but clicking make it cycle and show first one and then, after some other screen, the other one.

Any idea?

**Comment by odya** [comment]
Unfortunately, I don't have PV panels, so I can't test whether the values from them are accurate. However, I think there might be some additional register on more powerful inverter models.

**Comment by bradmatt275** [comment]
Through trial and error I'm pretty sure I have found the registers on my POW-HVM10.2M:

```
  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "PV 2 Voltage"
    id: pv2_voltage
    address: 4563
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    lambda: |-
      return swapBytes(x);
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "PV 2 Power"
    id: pv2_power
    address: 4564
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    lambda: |-
      return swapBytes(x);

  - platform: template
    name: "PV 2 Current"
    state_class: "measurement"
    device_class: current
    unit_of_measurement: "A"
    accuracy_decimals: 1
    icon: mdi:solar-power
    lambda: |-
      return id(pv2_power).state / id(pv2_voltage).state;
```

![image](https://github.com/odya/esphome-powmr-hybrid-inverter/assets/16756004/269f068d-16f0-4421-a973-255193eab15d)
