### ISSUE TITLE
does not read the values ​​"Grid Active, Grid Active, Grid Power, Grid Voltage"

### ISSUE THREAD

**Issue by Nando1497** [odya/esphome-powmr-hybrid-inverter#49]
Hi, I can't read the "Grid Active, Grid Active, Grid Power, Grid Voltage" values. I have an esp32: M5Stack Atom Lite ESP32.
![image](https://github.com/odya/esphome-powmr-hybrid-inverter/assets/88595006/2179e6b2-ece1-4875-8ee2-6792e053245a)

**Comment by Andrik45719** [comment]
Same problem, solved by change yaml to read states from 4553 register instead 4554

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "Grid Active"
    id: grid_active
    address: 4553
    register_type: holding
    bitmask: 0x200

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "On Battery"
    address: 4553
    register_type: holding
    bitmask: 0x100

**Comment by Nando1497** [comment]
hi, changing from 4554 to 4553 I read Grid Active and On Battery, but Grid Power not yet

**Comment by Nando1497** [comment]
It often happens that the "output Source Priority" and the "charger Source Priority" change

**Comment by davidebeatrici** [comment]
> It often happens that the "output Source Priority" and the "charger Source Priority" change

Related: #48

**Comment by rublin** [comment]
I have the same issue with my POW-HVM10.2M. 
Fixed **Grid Active** and **Grid Voltage** with this configuration in `inverter.yaml`:

```yaml
  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "Grid Active"
    id: grid_active
    address: 4553
    register_type: holding
    bitmask: 0x2000

  - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "On Battery"
    address: 4553
    register_type: holding
    bitmask: 0x100
```
But the **Grid Current** and **Grid Power** still don't work
