### ISSUE TITLE
using Pzem-004t V4 for Grid Power and pow-hvm10.2m inverter for Load Power results are different by a lot

### ISSUE THREAD

**Issue by SpankyDevil** [odya/esphome-powmr-hybrid-inverter#78]
Any idea how to resolve Grid Power and Load Power being so different, not sure which one is incorrect.

![Image](https://github.com/user-attachments/assets/474b74f1-2a26-451b-ae29-6336d49ea409)

![Image](https://github.com/user-attachments/assets/ce982904-2855-4358-95d5-177ddebf8bb3)

![Image](https://github.com/user-attachments/assets/337f5478-018f-4eb1-ad25-3f19b88a0223)

```
sensor:  
 - platform: modbus_controller
    modbus_controller_id: smg_inverter
    name: "Load Active Power"
    id: load_active_power
    address: 4513
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    accuracy_decimals: 0
    lambda: |-
      return swapBytes(x);
```

```
sensor:
  - platform: pzemac
    modbus_id: modbus_pzem
    update_interval: ${pzem_update_interval}
    voltage:
      name: "Grid PZEM Voltage"
      id: pzem_grid_voltage
      internal: true
      filters:
        - &mafilter quantile:
            window_size: 5
            send_every: 1
            send_first_at: 1
            quantile: .9
        - offset: ${pzem_voltage_offset}
    current:
      name: "Grid Current"
      id: pzem_grid_current
      filters:
        - *mafilter
        - offset: ${pzem_current_offset}
    power:
      name: "Grid Power"
      id: pzem_grid_power
      internal: true
      filters:
        - *mafilter
    power_factor:
      name: "Grid Power Factor"
      id: pzem_grid_power_factor
      filters:
        - *mafilter

  - platform: template
    name: "Grid Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    accuracy_decimals: 0
    update_interval: ${update_interval}
    lambda: |-
      return id(pzem_grid_current).state * id(pzem_grid_voltage).state * id(pzem_grid_power_factor).state;
```
